language: de
pipeline:
# No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# If you'd like to customize it, uncomment and adjust the pipeline.
# See https://rasa.com/docs/rasa/tuning-your-model for more information.

# From Rasa version 2.5 use of Spacy has to be clarified in another way. See notes: https://rasa.com/docs/rasa/migration-guide
# May need install of Spacy and Spacy language pack (https://spacy.io/usage/models):
# pip3 install -U pip setuptools wheel
# pip3 install -U spacy
# python3 -m spacy download de_core_news_sm
# Than use ->
#   - name: SpacyNLP
#     model: "de_core_news_sm"
   - name: WhitespaceTokenizer
   - name: RegexFeaturizer
   - name: LexicalSyntacticFeaturizer
   - name: CountVectorsFeaturizer
   - name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
   - name: DIETClassifier
     epochs: 100
     constrain_similarities: True
   - name: EntitySynonymMapper
   - name: ResponseSelector
     epochs: 100
# FAQ ResponseSelector
   - name: ResponseSelector
     epochs: 100
     retrieval_intent: faq
# Chitchat ResponseSelector
   - name: ResponseSelector
     epochs: 100
     retrieval_intent: chitchat
     constrain_similarities: true
   - name: FallbackClassifier
     threshold: 0.7
     ambiguity_threshold: 0.1
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
   - name: MemoizationPolicy
   - name: TEDPolicy
     max_history: 5
     epochs: 100
     constrain_similarities: true
   - name: RulePolicy
#     core_fallback_threshold: 0.4
#     core_fallback_action_name: "action_default_fallback"
#     enable_fallback_prediction: False
